---
title: "`r paste0(params$data$stdyDscr$citation$titlStmt$titl[[1]]$value, ' - README')`"
output: pdf_document
date: "`r format(Sys.Date(), '%B %d, %Y')`"
params:
  data: list
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r functions, include = FALSE}
return_authors <- function(authors) {
  r <- "**Authors:** \n\n"
  for(a in authors) {
    if(!is.null(a$affiliation)) {
      r <- paste0(r, "- ", a$name, " (", a$affiliation, ") \n")
    } else {
      r <- paste0(r, "- ", a$name, "\n")
    }
  }
  r
}

return_contributors <- function(contribs) {
  r <- "**Other support provided by:** \n\n"
  for(a in contribs) {
    if(!is.null(a$role) & !is.null(a$affiliation)) {
      r <- paste0(r, "- ", a$name, " (", a$affiliation, ") - ",
          a$role, "\n")
    } else if(!is.null(a$role) & is.null(a$affiliation)) {
      r <- paste0(r, "- ", a$name, " - ", a$role, "\n")
    } else if(is.null(a$role) & !is.null(a$affiliation)) {
      r <- paste0(r, "- ", a$name, " (", a$affiliation, ")\n")
    } else {
      r <- paste0(r,  "- ", a$name, "\n")
    }
  }
  r
}

return_producers <- function(producers) {
  r <- "**Produced by:** "
  for(p in producers) {
    if(!is.null(p$abbr)) {
      r <- paste0(r, p$name, " (", p$abbr, "), ")
    } else {
      r <- paste0(r, p$name, ", ")
    }
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_prodPlac <- function(prodPlac) {
  r <- "**Place of Production:** "
  for(p in prodPlac) {
    r <- paste0(r, p$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_prodDate <- function(prodDate) {
  r <- "**Date of Production:** "
  for(p in prodDate) {
    r <- paste0(r, p$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_fundAg <- function(fundAg) {
  r <- "**Funded by:** \n\n"
  for(f in fundAg) {
    if(!is.null(f$abbr) & !is.null(f$role)) {
      r <- paste0(r, "- ", f$name, " (", f$abbr, ") - ", f$role, "\n")
    } else if(is.null(f$abbr) & !is.null(f$role)) {
      r <- paste0(r, "- ", f$name, " - ", f$role, "\n")
    } else if(!is.null(f$abbr) & is.null(f$role)) {
      r <- paste0(r, "- ", f$name, " (", f$abbr, ") \n")
    } else {
      r <- paste0(r, "- ", f$name, "\n")
    }
  }
  r
}

check_for_stdyDscr <- function(stdyInfo) {
  r <- FALSE
  if(length(stdyInfo$abstract) > 0 | 
         length(stdyInfo$subject) > 0 |
         length(stdyInfo$sumDscr$anlyUnit) > 0 |
         length(stdyInfo$sumDscr$universe) > 0 |
         length(stdyInfo$sumDscr$nation) > 0 |
         length(stdyInfo$sumDscr$geogCover) > 0 |
         length(stdyInfo$sumDscr$geogUnit) > 0 |
         length(stdyInfo$sumDscr$timePrd) > 0 |
         length(stdyInfo$sumDscr$dataKind) > 0) { 
    r <- TRUE
  }
  r
}

return_abstract <- function(abstract) {
  r <- "**Abstract or Purpose** \n\n"
  for (a in abstract) {
    r <- paste0(r, a$value, "\n\n")
  }
  r
}

return_keywords <- function(keywords) {
  r <- "**Keywords:** "
  for (k in keywords) {
    r <- paste0(r, k$keyword, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
}

return_dataKind <- function(dataKind) {
  if(length(dataKind) == 1) {
    r <- "**Kind of Data:** "  
  } else {
    r <- "**Kinds of Data:** "            
  }
  for (n in dataKind) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_anlyUnit <- function(anlyUnit) {
  if(length(anlyUnit) == 1) {
    r <- "**Unit of Analysis:** "  
  } else {
    r <- "**Units of Analysis:** "
  }
  for (n in anlyUnit) {
    r <- paste0(r, n$group, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_universe <- function(universe) {
  r <- "**Universe:** "
  for (n in universe) {
    if(!is.null(n$clusion)) {
      if(n$clusion == "E") {
        r <- paste0(r, n$group, " (excluding), ")
      } else {
        r <- paste0(r, n$group, ", ")
      }
    } else {
      r <- paste0(r, n$group, ", ")
    }
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

check_for_geography <- function(sumDscr) {
  r <- FALSE
  if(length(sumDscr$nation) > 0 |
     length(sumDscr$geogCover) > 0 |
     length(sumDscr$geogUnit) > 0) {
    r <- TRUE
  }
  r
}

return_nation <- function(nation) {
  if(length(nation) == 1) {
    r <- "- **Nation:** " 
  } else {
    r <- "- **Nations:** "
  }
  for (n in nation) {
    if(!is.null(n$abbr)) {
      r <- paste0(r, n$value, " (", n$abbr, "), ")
    } else {
      r <- paste0(r, n$value, ", ")
    }
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_geogCover <- function(geogCover) {
  r <- "- **Geographic coverage:** "
  for (n in geogCover) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_geogUnit <- function(geogUnit) {
  if(length(geogUnit) == 1) {
    r <- "- **Geographic Unit:** "  
  } else {
    r <- "- **Geographic Units:** "
  }
  for (n in geogUnit) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_timePrd <- function(timePrd) {
  r <- "\n\n### Time Periods \n\n"
  ds <- tibble(value = character(),
               date = character(),
               event = character(),
               cycle = character()
  )
  for (n in timePrd) {
    ds <- add_row(ds, value = n$value, date = n$date, event = n$event, cycle = n$cycle)
  }
  cycles = unique(ds$cycle)
  for(c in cycles) {
    subset <- ds %>% filter(cycle == c)
    if(length(subset$event) == 1) {
      r <- paste0(r, "- **", c, ": **", subset$date[1], " (", subset$event[1], ") \n")
    } else {
      start <- subset %>% filter(event == "start") %>% select(value)
      end <- subset %>% filter(event == "end") %>% select(value)
      r <- paste0(r, "- **", c, ": **", start, " to ", end, "\n")
    }
  }
  r
}

check_for_dataColl <- function(dataColl, collDate) {
  r <- FALSE
  if(length(dataColl$dataCollector) > 0 |
         length(dataColl$collMode) > 0 |
         length(dataColl$collectorTraining) > 0 |
         length(dataColl$collSitu) > 0 |
         length(dataColl$timeMeth) > 0 |
         length(collDate) > 0 |
         length(dataColl$resInstru) > 0 |
         length(dataColl$instrumentDevelopment) > 0 |
         length(dataColl$sampProc) > 0 |
         length(dataColl$ConOps) > 0 |
         length(dataColl$actMin) > 0 |
         length(dataColl$deviat) > 0 |
         length(dataColl$frequenc) > 0) { 
    r <- TRUE
  }
  r
}

return_dataCollector <- function(collectors) {
  if(length(collectors) == 1) {
    r <- "**Data Collector:** "  
  } else {
    r <- "**Data Collector:** "  
  }
  for (n in collectors) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_collMode <- function(collMode) {
  if(length(collMode) == 1) {
    r <- "**Mode of collection:** "  
  } else {
    r <- "**Modes of collection:** "  
  }
  for (n in collMode) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_collSitu <- function(collSitu) {
  r <- "**Characteristics of Data Collection Situation:** "
  for (n in collSitu) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_collectorTraining <- function(training) {
  r <- "**Collector Training:** "  
  
  for (n in training) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_timeMeth <- function(timeMeth) {
  if(length(timeMeth) == 1) {
    r <- "**Time method:** "  
  } else {
    r <- "**Time methods:** "  
  }
  for (n in timeMeth) {
    r <- paste0(r, n$value, ", ")
  }
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_collDate <- function(collDate) {
  r <- "\n\n### Dates of Data Collection \n\n"
  ds <- tibble(value = character(),
               date = character(),
               event = character(),
               cycle = character()
  )
  for (n in collDate) {
    ds <- add_row(ds, value = n$value, date = n$date, event = n$event, cycle = n$cycle)
  }
  cycles = unique(ds$cycle)
  for(c in cycles) {
    subset <- ds %>% filter(cycle == c)
    if(length(subset$event) == 1) {
      r <- paste0(r, "- **", c, ": **", subset$date[1], " (", subset$event[1], ") \n")
    } else {
      start <- subset %>% filter(event == "start") %>% select(value)
      end <- subset %>% filter(event == "end") %>% select(value)
      r <- paste0(r, "- **", c, ": **", start, " to ", end, "\n")
    }
  }
  r
}

return_resInstru <- function(resInstru) {
  if(length(resInstru) == 1) {
    r <- "- **Research Instrument:** "
  } else {
    r <- "- **Research Instruments:** "
  }
  for (n in resInstru) {
    r <- paste0(r, n$value, ", ")
  }
  
  r <- substr(r, 1, nchar(r)-2)
  r
}

return_instrumentDevelopment <- function(instrumentDevelopment) {
  r <- "- **Instrument Development:** "
  for (n in instrumentDevelopment) {
    r <- paste0(r, n$value, ", ")
  }

  r <- substr(r, 1, nchar(r)-2)
  r
}

return_sampProc <- function(sampProc) {
  if(length(resInstru) == 1) {
    r <- "- **Sampling Procedure:** "
  } else {
    r <- "- **Sampling Procedures:** "
  }
  for (n in sampProc) {
    r <- paste0(r, n$value, ", ")
  }

  r <- substr(r, 1, nchar(r)-2)
  r
}

return_ConOps <- function(ConOps) {
  if(length(ConOps) == 1) {
    r <- "- **Control Operation:** "
  } else {
    r <- "- **Control Operations:** "
  }
  for (n in ConOps) {
    r <- paste0(r, n$value, ", ")
  }

  r <- substr(r, 1, nchar(r)-2)
  r
}

return_actMin <- function(actMin) {
  if(length(actMin) == 1) {
    r <- "- **Action to Minimize Loss:** "
  } else {
    r <- "- **Actions to Minimize Loss:** "
  }
  for (n in actMin) {
    r <- paste0(r, n$value, ", ")
  }

  r <- substr(r, 1, nchar(r)-2)
  r
}

return_deviat <- function(deviat) {
  if(length(deviat) == 1) {
    r <- "- **Major Deviation:** "
  } else {
    r <- "- **Major Deviations:** "
  }
  for (n in deviat) {
    r <- paste0(r, n$value, ", ")
  }

  r <- substr(r, 1, nchar(r)-2)
  r
}

return_frequenc <- function(frequenc) {
  r <- "- **Frequency of Collection:** "
  for (n in frequenc) {
    r <- paste0(r, n$value, ", ")
  }

  r <- substr(r, 1, nchar(r)-2)
  r
}

check_for_researchInstr <- function(dataColl) {
  r <- FALSE
  if(length(dataColl$resInstru) > 0 |
     length(dataColl$instrumentDevelopment) > 0) { 
    r <- TRUE
  }
  r
}

check_for_sampling <- function(dataColl) {
  r <- FALSE
  if(length(dataColl$sampProc) > 0 |
     length(dataColl$ConOps) > 0 |
     length(dataColl$actMin) > 0 |
     length(dataColl$deviat) > 0 |
     length(dataColl$frequenc) > 0) { 
    r <- TRUE
  }
  r
}

check_for_othrStdyMat <- function(othrStdyMat) {
  r <- FALSE
  if(length(othrStdyMat$relMat) > 0 |
     length(othrStdyMat$relStdy) > 0 |
     length(othrStdyMat$relPubl) > 0 |
     length(othrStdyMat$othRefs) > 0) {
    r <- TRUE
  }
  r
}

return_relMat <- function(relMat) {
  r <- "**Related Materials:**\n\n"
  for (n in relMat) {
    if(!is.null(n$biblCit)) {
      r <- paste0(r, n$biblCit, "\n\n")
      if(!is.null(n$description)) {
        r <- paste0(r, "- *", n$description, "*\n\n")
      }
    } else if(is.null(n$biblCit) & !is.null(n$description)) {
      r <- paste0(r, "*", n$description, "*\n\n")
    }  
  }
  r
}

return_relStdy <- function(relStdy) {
  r <- "**Related Studies:**\n\n"
  for (n in relStdy) {
    if(!is.null(n$biblCit)) {
      r <- paste0(r, n$biblCit, "\n\n")
      if(!is.null(n$description)) {
        r <- paste0(r, "- *", n$description, "*\n\n")
      }
    } else if(is.null(n$biblCit) & !is.null(n$description)) {
      r <- paste0(r, "*", n$description, "*\n\n")
    }  
  }
  r
}

return_relPubl <- function(relPubl) {
  r <- "**Related Publications:**\n\n"
  for (n in relPubl) {
    if(!is.null(n$biblCit)) {
      r <- paste0(r, n$biblCit, "\n\n")
      if(!is.null(n$description)) {
        r <- paste0(r, "- *", n$description, "*\n\n")
      }
    } else if(is.null(n$biblCit) & !is.null(n$description)) {
      r <- paste0(r, "*", n$description, "*\n\n")
    }  
  }
  r
}

return_othRefs <- function(othRefs) {
  r <- "**Other References:**\n\n"
  for (n in othRefs) {
    if(!is.null(n$biblCit)) {
      r <- paste0(r, n$biblCit, "\n\n")
      if(!is.null(n$description)) {
        r <- paste0(r, "- *", n$description, "*\n\n")
      }
    } else if(is.null(n$biblCit) & !is.null(n$description)) {
      r <- paste0(r, "*", n$description, "*\n\n")
    }  
  }
  r
}

return_varGrp <- function(varGrp) {
  r <- ""
  for (d in varGrp) {
    r <- paste0(r, "### ", d$name[[1]], "\n\n")
    if(length(d$labl) > 0) {
      r <- paste0(r, "- **Label(s): **")
      for(l in d$labl) {
        r <- paste0(r, l$value, ", ")
      }
      r <- substr(r, 1, nchar(r)-2)
      r <- paste0(r, "\n\n")
    }
    if(length(d$defntn) > 0) {
      r <- paste0(r, "- **Definition(s):** ")
      for(n in d$defntn) {
        r <- paste0(r, n$value, ", ")
      }
      r <- substr(r, 1, nchar(r)-2)
      r <- paste0(r, "\n")
    }
    if(length(d$universe) > 0) {
      r <- paste0(r, "- **Universe(s):** ")
      for(n in d$universe) {
        if(!is.null(n$clusion) & n$clusion == "E") {
          r <- paste0(r, n$group, " (excluding), ")
        } else {
          r <- paste0(r, n$group, ", ")
        }
      }
      r <- substr(r, 1, nchar(r)-2)
      r <- paste0(r, "\n")
    }
    if(length(d$concept) > 0) {
      r <- paste0(r, "- **Concept(s): **")
      for(c in d$concept) {
        r <- paste0(r, c$value, ", ")
      }
      r <- substr(r, 1, nchar(r)-2)
      r <- paste0(r, "\n")
    }
    r <- paste0(r, "\n\n")
  }
  r
}
```

```{r echo = FALSE, results='asis'}

if(length(params$data$stdyDscr$citation$rspStmt$AuthEnty) > 0) {
  authors <- return_authors(params$data$stdyDscr$citation$rspStmt$AuthEnty)
  cat(authors, "\n")
}

if(length(params$data$stdyDscr$citation$rspStmt$othId) > 0) {
  contribs <- return_contributors(params$data$stdyDscr$citation$rspStmt$othId)
  cat(contribs, "\n")
}

if(length(params$data$stdyDscr$citation$prodStmt$producer) > 0) {
  producers <- return_producers(params$data$stdyDscr$citation$prodStmt$producer)
  cat(producers, "\n\n")
}

if(length(params$data$stdyDscr$citation$prodStmt$prodPlac) > 0) {
  prodPlac <- return_prodPlac(params$data$stdyDscr$citation$prodStmt$prodPlac)
  cat(prodPlac, "\n\n")
}

if(length(params$data$stdyDscr$citation$prodStmt$prodDate) > 0) {
  prodDate <- return_prodDate(params$data$stdyDscr$citation$prodStmt$prodDate)
  cat(prodDate, "\n\n")
}

if(length(params$data$stdyDscr$citation$prodStmt$fundAg) > 0) {
  fundAg <- return_fundAg(params$data$stdyDscr$citation$prodStmt$fundAg)
  cat(fundAg, "\n\n")
}

if(check_for_stdyDscr(params$data$stdyDscr$stdyInfo)) {
  cat("---\n\n## Study Information", "\n\n")
}

if(length(params$data$stdyDscr$stdyInfo$abstract) > 0) {
  abstract <- return_abstract(params$data$stdyDscr$stdyInfo$abstract)
  cat(abstract, "\n\n")
}

if(length(params$data$stdyDscr$stdyInfo$subject) > 0) {
  keywords <- return_keywords(params$data$stdyDscr$stdyInfo$subject)
  cat(keywords, "\n\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$dataKind) > 0) {
  dataKind <- return_dataKind(params$data$stdyDscr$stdyInfo$sumDscr$dataKind)
  cat(dataKind, "\n\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$anlyUnit) > 0) {
  anlyUnit <- return_anlyUnit(params$data$stdyDscr$stdyInfo$sumDscr$anlyUnit)
  cat(anlyUnit, "\n\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$universe) > 0) {
  universe <- return_universe(params$data$stdyDscr$stdyInfo$sumDscr$universe)
  cat(universe, "\n\n")
}

if(check_for_geography(params$data$stdyDscr$stdyInfo$sumDscr)) {
  cat("### Geography", "\n\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$nation) > 0) {
  nation <- return_nation(params$data$stdyDscr$stdyInfo$sumDscr$nation)
  cat(nation, "\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$geogCover) > 0) {
  geogCover <- return_geogCover(params$data$stdyDscr$stdyInfo$sumDscr$geogCover)
  cat(geogCover, "\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$geogUnit) > 0) {
  geogUnit <- return_geogUnit(params$data$stdyDscr$stdyInfo$sumDscr$geogUnit)
  cat(geogUnit, "\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$timePrd) > 0) {
  timePrd <- return_timePrd(params$data$stdyDscr$stdyInfo$sumDscr$timePrd)
  cat(timePrd, "\n\n")
}

if(check_for_dataColl(params$data$stdyDscr$method$dataColl, params$data$stdyDscr$stdyInfo$sumDscr$dataColl)) {
  cat("---\n\n## Data Collection", "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$dataCollector) > 0) {
  dataCollector <- return_dataCollector(params$data$stdyDscr$method$dataColl$dataCollector)
  cat(dataCollector, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$collMode) > 0) {
  collMode <- return_collMode(params$data$stdyDscr$method$dataColl$collMode)
  cat(collMode, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$collectorTraining) > 0) {
  collectorTraining <- return_collectorTraining(params$data$stdyDscr$method$dataColl$collectorTraining)
  cat(collectorTraining, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$collSitu) > 0) {
  collSitu <- return_collSitu(params$data$stdyDscr$method$dataColl$collSitu)
  cat(collSitu, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$timeMeth) > 0) {
  timeMeth <- return_timeMeth(params$data$stdyDscr$method$dataColl$timeMeth)
  cat(timeMeth, "\n\n")
}

if(length(params$data$stdyDscr$stdyInfo$sumDscr$collDate) > 0) {
  collDate <- return_collDate(params$data$stdyDscr$stdyInfo$sumDscr$collDate)
  cat(collDate, "\n\n")
}

if(check_for_researchInstr(params$data$stdyDscr$method$dataColl)) {
  cat("### Research Instrument", "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$resInstru) > 0) {
  resInstru <- return_resInstru(params$data$stdyDscr$method$dataColl$resInstru)
  cat(resInstru, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$instrumentDevelopment) > 0) {
  instrumentDevelopment <- return_instrumentDevelopment(params$data$stdyDscr$method$dataColl$instrumentDevelopment)
  cat(instrumentDevelopment, "\n\n")
}

if(check_for_sampling(params$data$stdyDscr$method$dataColl)) {
  cat("### Sampling Procedure", "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$sampProc) > 0) {
  sampProc <- return_sampProc(params$data$stdyDscr$method$dataColl$sampProc)
  cat(sampProc, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$ConOps) > 0) {
  ConOps <- return_ConOps(params$data$stdyDscr$method$dataColl$ConOps)
  cat(ConOps, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$actMin) > 0) {
  actMin <- return_actMin(params$data$stdyDscr$method$dataColl$actMin)
  cat(actMin, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$deviat) > 0) {
  deviat <- return_deviat(params$data$stdyDscr$method$dataColl$deviat)
  cat(deviat, "\n\n")
}

if(length(params$data$stdyDscr$method$dataColl$frequenc) > 0) {
  frequenc <- return_frequenc(params$data$stdyDscr$method$dataColl$frequenc)
  cat(frequenc, "\n\n")
}

if(check_for_othrStdyMat(params$data$stdyDscr$othrStdyMat)) {
  cat("## Bibliography", "\n\n")
}

if(length(params$data$stdyDscr$othrStdyMat$relMat) > 0) {
  relMat <- return_relMat(params$data$stdyDscr$othrStdyMat$relMat)
  cat(relMat, "\n\n")
}

if(length(params$data$stdyDscr$othrStdyMat$relStdy) > 0) {
  relStdy <- return_relStdy(params$data$stdyDscr$othrStdyMat$relStdy)
  cat(relStdy, "\n\n")
}

if(length(params$data$stdyDscr$othrStdyMat$relPubl) > 0) {
  relPubl <- return_relPubl(params$data$stdyDscr$othrStdyMat$relPubl)
  cat(relPubl, "\n\n")
}

if(length(params$data$stdyDscr$othrStdyMat$othRefs) > 0) {
  othRefs <- return_othRefs(params$data$stdyDscr$othrStdyMat$othRefs)
  cat(othRefs, "\n\n")
}

if(length(params$data$dataDscr$varGrp) > 0) {
  cat("---\n\n## Variable Groups", "\n\n")
  varGrp <- return_varGrp(params$data$dataDscr$varGrp)
  cat(varGrp, "\n")
}

```
